// Code generated by scripts/build-wasm.sh. DO NOT EDIT.
//
// The integrity pin for the Argon2id kernel. web/lib/argon2.ts refuses to
// instantiate any bytes that do not hash to ARGON2_WASM_SHA512, so a
// substituted or corrupted module fails closed rather than silently deriving
// the wrong key.
//
// Verify independently:
//   ./scripts/build-wasm.sh          # rebuild from source
//   node scripts/verify-wasm.mjs     # check the artifact against Go's own argon2
//
// Built with go1.26.3 from internal/wasm/argon2/main.go.

export const ARGON2_WASM_URL = "/static/argon2.8850873c407e418e.wasm";
export const ARGON2_WASM_SHA512 = "YiuayQH9QPW0rb95qxlEBipQc38/tOADZKld7czwzuCEcnOhgBMUKh503pZPjaSqYKWQ23ueOlECvmOBuuCn7A==";
export const ARGON2_WASM_BYTES = 1893524;
