#!/usr/bin/env bash
#
# build-wasm.sh : compile the Argon2id kernel to WebAssembly, reproducibly.
#
# The output is committed to the repository (web/static/argon2.<hash>.wasm)
# together with the generated pin in web/lib/argon2-manifest.ts, so a normal
# ./start.sh needs no wasm toolchain and no build step. Re-run this only when
# internal/wasm/argon2/main.go or the pinned Go version changes.
#
# Reproducibility is the point, not a nicety. This is a zero-knowledge product
# whose source is public: the only reason to trust the binary blob the browser
# executes is that you can rebuild it yourself and get the same bytes. So:
#
#   -trimpath        strips absolute build paths from the binary
#   -buildvcs=false  keeps git state out of it
#   -ldflags=-s -w   drops the symbol table and DWARF, which embed paths
#   GOFLAGS=-mod=readonly  pins dependencies to go.mod/go.sum exactly
#
# Given the same Go version and the same go.sum, the SHA-256 below is fixed.
# It is printed on every build; if it changes and you did not change the
# source, something else did.
#
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$PROJECT_DIR"

# The Go version is part of the artifact: a different compiler emits different
# (still correct) wasm. Pinning it is what makes "rebuild and compare" a
# meaningful check rather than a coin flip.
PINNED_GO="go1.26.3"
ACTUAL_GO="$(go env GOVERSION)"

SRC_DIR="internal/wasm/argon2"
OUT_DIR="web/static"
MANIFEST="web/lib/argon2-manifest.ts"
TMP_WASM="$(mktemp -t argon2wasm)"
trap 'rm -f "$TMP_WASM"' EXIT

echo "▸ building $SRC_DIR → wasip1/wasm"
if [ "$ACTUAL_GO" != "$PINNED_GO" ]; then
  echo "  ⚠ toolchain is $ACTUAL_GO, artifact was pinned at $PINNED_GO."
  echo "    The build will succeed but the digest will not match the committed one."
fi

GOOS=wasip1 GOARCH=wasm GOFLAGS=-mod=readonly \
  go build -trimpath -buildvcs=false -buildmode=c-shared \
  -ldflags="-s -w" -o "$TMP_WASM" ./"$SRC_DIR"

SHA256_HEX="$(shasum -a 256 "$TMP_WASM" | cut -d' ' -f1)"
SHA512_B64="$(openssl dgst -sha512 -binary "$TMP_WASM" | openssl base64 -A)"
SHORT="${SHA256_HEX:0:16}"
BYTES="$(wc -c < "$TMP_WASM" | tr -d ' ')"
FILENAME="argon2.${SHORT}.wasm"

# Content-addressed filename: a cache that still holds a previous build simply
# misses instead of serving bytes whose digest no longer matches, which would
# otherwise present to the user as "unlock is broken".
rm -f "$OUT_DIR"/argon2.*.wasm
cp "$TMP_WASM" "$OUT_DIR/$FILENAME"

cat > "$MANIFEST" <<EOF
// Code generated by scripts/build-wasm.sh. DO NOT EDIT.
//
// The integrity pin for the Argon2id kernel. web/lib/argon2.ts refuses to
// instantiate any bytes that do not hash to ARGON2_WASM_SHA512, so a
// substituted or corrupted module fails closed rather than silently deriving
// the wrong key.
//
// Verify independently:
//   ./scripts/build-wasm.sh          # rebuild from source
//   node scripts/verify-wasm.mjs     # check the artifact against Go's own argon2
//
// Built with $PINNED_GO from $SRC_DIR/main.go.

export const ARGON2_WASM_URL = "/static/$FILENAME";
export const ARGON2_WASM_SHA512 = "$SHA512_B64";
export const ARGON2_WASM_BYTES = $BYTES;
EOF

echo "  $OUT_DIR/$FILENAME"
echo "  $BYTES bytes  sha256:$SHA256_HEX"
echo "  wrote $MANIFEST"

if command -v node >/dev/null 2>&1; then
  echo "▸ verifying against Go's native argon2"
  node scripts/verify-wasm.mjs
else
  echo "  ⚠ node not found — skipping known-answer verification."
  echo "    Run 'node scripts/verify-wasm.mjs' before committing this artifact."
fi