// verify-wasm.mjs : prove the committed Argon2id wasm artifact is the real thing.
//
//   node scripts/verify-wasm.mjs
//
// Two independent claims are checked, and both matter:
//
//   1. The artifact on disk hashes to the digest web/lib/argon2-manifest.ts
//      pins. That is the same check the browser makes before it will execute
//      the module, so a failure here means the app would refuse to unlock.
//
//   2. The module reproduces known answers generated by Go's own
//      golang.org/x/crypto/argon2 — including a vector at the exact
//      production parameters. This is what rules out a module that loads
//      cleanly and derives the wrong key, which no digest check can catch:
//      a digest only proves the bytes are the bytes someone intended.
//
// The kernel under test is web/static/argon2-kernel.js — the very module the
// browser worker imports, not a reimplementation of it.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { instantiateKernel } from "../web/static/argon2-kernel.js";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

function readManifest() {
  const source = fs.readFileSync(path.join(ROOT, "web/lib/argon2-manifest.ts"), "utf8");
  const pick = (name) => {
    const match = source.match(new RegExp(`export const ${name} = "([^"]*)"`));
    if (!match) throw new Error(`argon2-manifest.ts is missing ${name}`);
    return match[1];
  };
  return { url: pick("ARGON2_WASM_URL"), sha512: pick("ARGON2_WASM_SHA512") };
}

const manifest = readManifest();
const wasmPath = path.join(ROOT, "web", manifest.url.replace(/^\//, ""));

if (!fs.existsSync(wasmPath)) {
  console.error(`✖ artifact missing: ${path.relative(ROOT, wasmPath)}`);
  console.error("  run ./scripts/build-wasm.sh");
  process.exit(1);
}

const wasmBytes = new Uint8Array(fs.readFileSync(wasmPath));
console.log(`▸ ${path.relative(ROOT, wasmPath)} (${wasmBytes.length} bytes)`);

let kernel;
try {
  // Throws on digest mismatch — claim (1).
  kernel = await instantiateKernel(wasmBytes, manifest.sha512);
} catch (err) {
  console.error(`✖ ${err.message}`);
  process.exit(1);
}
console.log(`  integrity ok — sha512-${manifest.sha512.slice(0, 24)}…`);

const vectors = JSON.parse(fs.readFileSync(path.join(ROOT, "internal/crypto/testdata/argon2_vectors.json"), "utf8"));
const fromB64Url = (s) => new Uint8Array(Buffer.from(s.replace(/-/g, "+").replace(/_/g, "/"), "base64"));
const toHex = (b) => Buffer.from(b).toString("hex");

let failures = 0;
for (const v of vectors) {
  const started = Date.now();
  let got;
  try {
    got = toHex(
      kernel.argon2id(fromB64Url(v.password), fromB64Url(v.salt), {
        time: v.time,
        memoryKiB: v.memoryKiB,
        lanes: v.lanes,
        outLen: v.outLen,
      }),
    );
  } catch (err) {
    got = `threw: ${err.message}`;
  }
  const ok = got === v.want;
  if (!ok) failures++;
  console.log(
    `  ${ok ? "✓" : "✖"} ${v.note}  [t=${v.time} m=${v.memoryKiB}KiB p=${v.lanes} len=${v.outLen}] ${Date.now() - started}ms`,
  );
  if (!ok) {
    console.log(`      want ${v.want}`);
    console.log(`      got  ${got}`);
  }
}
kernel.zero();

if (failures > 0) {
  console.error(`\n✖ ${failures}/${vectors.length} known-answer tests failed — do not ship this artifact.`);
  process.exit(1);
}
console.log(`\n✓ ${vectors.length}/${vectors.length} known-answer tests match Go's native argon2.`);